# Netlify Configuration for Instagram Clone
# This file configures build settings, redirects, and headers

[build]
  # Build command - adjust based on your framework
  command = "npm run build"
  
  # Publish directory - adjust based on your framework
  # Vite/React: "dist"
  # Create React App: "build"
  # Next.js: ".next" (requires @netlify/plugin-nextjs)
  publish = "dist"
  
  # Functions directory for serverless functions (optional)
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# SPA redirect - ensures client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Development context (branch: develop)
[context.develop]
  command = "npm run build"
  [context.develop.environment]
    NODE_ENV = "development"

# Production context
[context.production]
  [context.production.environment]
    NODE_ENV = "production"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Deploy Preview context
[context.deploy-preview]
  command = "npm run build"
